language: node_js
node_js:
- lts/*
- '8'
- '7'
- '6'

sudo: required
addons:
  chrome: stable

install:
  - npm install
  - echo TRAVIS_TAG=${TRAVIS_TAG}
  - echo TRAVIS_TAG=${TRAVIS_BRANCH}
  - git fetch --tags
  - npm run build

cache:
  directories:
  - node_modules

notifications:
  slack:
    email : false
    secure: RJiPWGMnu05o/ywMqJup7FA4+TaXQ9DyGGfou9a0a37Ptm+JeK8bYOZEoDG7xGwP+VMXtYbn9c3WCf0bPrt1+zMeR3s0VRWTyjwTwwD60uob8yv9ppe+41yg8/77Myc51fdWFZD/I6KdorCP8G9Uhg4xQAVq1fuW798yDy64LO/1uXvxE7oWhwpg1ezuRNBB6N0LYAH4kOp8Z5DSEgmQZeu6S+NEk/b0xG6sHqwIPVCfz3BpI4okp2AsaUo67pwT6AOtw0QtoXMab4mSda1luLV5E3PI4scWvgjbeq9KB7tAOtRfp3N0bfY2bx5GHb3GS5JQ0gwC5X8wJdnIwo31UzcEwU3u7o2g0Sotznf3nZcHjgDIEJos6YPefb7giSk0HV6JrXCDFquiaASgKjzwp3yGjiHOQyNv1KwKwEwalFzze4HbiiskEe8nnofBxpv8W/YesnpH3KLSkoisD17hRttklDTqj1ly0TsLleqxCphB2pDk8mefgSoBE005r90V9gxcIWyEvtZXz0QMFmFXob6A6UAV//KIcrzA21kPu4b54CaJjqFbQwPxNA6bH4boFnO1IE6LF7Lt5IjwAzlCMzLAUGa5/K99XSIh3Iq980tOCACZ+mw14HgthVIVeXhsS1VJe4mcmaw9WGO0tChbT0eK5SJuHK7DMGo/WJZ7nPM=


after_success:
  - npm install -g travis-deploy-once
  - git checkout master
  - git add --all
  - git commit -m "build by travisCI"
  - 'export OBNIZ_COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"'
  - 'export OBNIZ_COMMIT_INFO="$(git log -1 $TRAVIS_COMMIT --pretty="%d")"'
  - echo OBNIZ_COMMITTER_EMAIL=${OBNIZ_COMMITTER_EMAIL}
  - echo OBNIZ_COMMIT_INFO=${OBNIZ_COMMIT_INFO}
  - echo TRAVIS_COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}
  - '[ "$TRAVIS_TAG" = ""  ] && [ "$TRAVIS_BRANCH" = "master"  ] && travis-deploy-once  && OBNIZ_DEPLOY=1' #ほかのプロセス終了確認
  - 'if [[ ${OBNIZ_COMMIT_INFO} = *"${TRAVIS_COMMIT_MESSAGE}"* ]] ; then OBNIZ_DEPLOY=0 ; fi;'
  - echo OBNIZ_DEPLOY=${OBNIZ_DEPLOY}


before_deploy :
  - npm version patch
  - git push --tags --force https://${GITHUB_TOKEN}@github.com/obniz/obniz.git master
  - git fetch
  - git log --oneline --graph --decorate -5
  - echo OBNIZ_DEPLOY=${OBNIZ_DEPLOY}



deploy:
  provider: npm
  email: kido@9wick.com
  api_key:
    secure: "tJlQWwTBZY4FfGn6C0rQJUI9jz05VIICTN0CnAqH1iJshIFBGHtpYhMGueWewQMsp3UjO1DJ63ioHRylMWsZi/m/pQx3KgOflPc1WrNyoF/GFOCNG9C3mIX/i7NlVSeUtf5pDrt1ssIeWG6+W7Q1StaE65S337DYQ5zeMuNeJVQCL1yZWqqzcKXJkpikHrdyF5QlDgBJCLXwg6AmTmCJUnoyX4oOxGEFpBJir43Mx5kpWrOZfijBP6OcjXO4kjMvR58UjxUQ9BwcI0QHauo8XqpJSkYd0LbQNx/JKvfI7sobgmsmIC9ncFRE1kelltm/B/XeE/lMUcQO7Nz0ztZGjtwWWYwlRk4Opv0FnzZTd/+y4Q3APJI/VLmKLiKT+mTvlrAAcuriUXffnjcVTKzT5X9onVptXpg69qltjGbPZtTyt7UulT1K0exsSLAyWujGjRdRHofmcfTmc5k1rDBnEOLa8bCocKA7y4HtCDaLnWAkMGlLpn/ucPJduGFwM9h9WATn/nl6StU9WC8Gcs5Rp4t4tMGh5eEAIqItofYNjYk1UDuWQn6uuuaGvCljTjm8ckAohfcrBCkXR2dLeFco7Cs1ZQuGkrQq/2tY54GzIcMBBEmbLtuGsQrMww2G0s/TeeN9+HfqVhRykMglARnk1c4MhaKIomGEgqo7jNW/Rcw="
  on:
    branch: master
    repo: obniz/obniz
    tags: false
    node: lts/*
    condition: ' ${OBNIZ_DEPLOY} = 1  '

  skip_cleanup: true

env:
  global:
    - GIT_COMMITTER_NAME=deploy@travis-ci.org
    - GIT_COMMITTER_EMAIL=deploy@travis-ci.org
    - GIT_AUTHOR_NAME=deploy@travis-ci.org
    - GIT_AUTHOR_EMAIL=deploy@travis-ci.org