language: node_js
node_js:
- lts/*
- '8'
- '7'

cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: RJiPWGMnu05o/ywMqJup7FA4+TaXQ9DyGGfou9a0a37Ptm+JeK8bYOZEoDG7xGwP+VMXtYbn9c3WCf0bPrt1+zMeR3s0VRWTyjwTwwD60uob8yv9ppe+41yg8/77Myc51fdWFZD/I6KdorCP8G9Uhg4xQAVq1fuW798yDy64LO/1uXvxE7oWhwpg1ezuRNBB6N0LYAH4kOp8Z5DSEgmQZeu6S+NEk/b0xG6sHqwIPVCfz3BpI4okp2AsaUo67pwT6AOtw0QtoXMab4mSda1luLV5E3PI4scWvgjbeq9KB7tAOtRfp3N0bfY2bx5GHb3GS5JQ0gwC5X8wJdnIwo31UzcEwU3u7o2g0Sotznf3nZcHjgDIEJos6YPefb7giSk0HV6JrXCDFquiaASgKjzwp3yGjiHOQyNv1KwKwEwalFzze4HbiiskEe8nnofBxpv8W/YesnpH3KLSkoisD17hRttklDTqj1ly0TsLleqxCphB2pDk8mefgSoBE005r90V9gxcIWyEvtZXz0QMFmFXob6A6UAV//KIcrzA21kPu4b54CaJjqFbQwPxNA6bH4boFnO1IE6LF7Lt5IjwAzlCMzLAUGa5/K99XSIh3Iq980tOCACZ+mw14HgthVIVeXhsS1VJe4mcmaw9WGO0tChbT0eK5SJuHK7DMGo/WJZ7nPM=